In [614]:
#100 numpy exercise
#by Golubev Ilya

In [516]:
#1
#Import the numpy package under the name np
import numpy as np 


In [517]:
#2
#Print the numpy version and the configuration
print(np.__version__)
np.show_config()


1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [518]:
#3
#Create a null vector of size 10
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [519]:
#4
#How to find the memory size of any array
print("%d bytes" % (np.zeros((10)).size * np.zeros((10)).itemsize))

80 bytes


In [520]:
#5
# How to get the documentation of the numpy add function from the command line?
np.info(np.add)

In [521]:
#6
#Create a null vector of size 10 but the fifth value which is 1
A = np.zeros(10)
A[4] = 1
print(A)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [522]:
#7
# Create a vector with values ranging from 10 to 49
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [523]:
#8
# Reverse a vector (first element becomes last)
A = np.arange(50)
A = A[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [524]:
#9
#Create a 3x3 matrix with values ranging from 0 to 8
print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [525]:
#10
#Find indices of non-zero elements from [1,2,0,0,4,0]
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


In [526]:
#11
#Create a 3x3 identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [527]:
#12
#Create a 3x3x3 array with random values
print(np.random.random((3,3,3)))

[[[0.63668545 0.14492115 0.44396308]
  [0.96964641 0.5950581  0.32203427]
  [0.36509843 0.52866272 0.77479813]]

 [[0.64117142 0.1832511  0.5086347 ]
  [0.64865387 0.4700706  0.8521391 ]
  [0.95558144 0.3780524  0.97965462]]

 [[0.98453482 0.25165116 0.08960057]
  [0.38067531 0.03822424 0.86701266]
  [0.7132265  0.94711983 0.33785834]]]


In [528]:
#13
#Create a 10x10 array with random values and find the minimum and maximum values
A = np.random.random((10,10))
print(A.min(), A.min())

0.01263399963886458 0.01263399963886458


In [529]:
#14
#Create a random vector of size 30 and find the mean value
print(np.random.random(30).mean())

0.3884792321537862


In [530]:
#15
#Create a 2d array with 1 on the border and 0 inside
A = np.ones((10,10))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [531]:
#16
#How to add a border (filled with 0's) around an existing array?
A = np.pad(np.ones((5,5)), pad_width=1, mode='constant', constant_values=0)
print(A)
A[:, [0, -1]] = 0
A[[0, -1], :] = 0
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [532]:
#17
#What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [533]:
#18
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
print(np.diag(1+np.arange(4),k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [534]:
#19
#Create a 8x8 matrix and fill it with a checkerboard pattern
A = np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [535]:
#20
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [536]:
#21
#Create a checkerboard 8x8 matrix using the tile function
A = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [537]:
#22
#Normalize a 5x5 random matrix
A= np.random.random((5,5))
Amax = A.max()
Amin = A.min()
A = (A - xmin)/(xmax - xmin)
print(A)

[[0.77304009 0.45356066 0.73286461 0.15472221 0.40315846]
 [0.66458035 0.2391287  0.92393601 0.20577046 0.27914276]
 [0.9779742  0.63836615 0.66731972 0.7952339  0.43369532]
 [0.25248493 0.73609211 0.35211926 0.32884184 0.64360066]
 [0.06000799 0.86027898 0.03258818 0.46667466 0.23500555]]


In [538]:
#23
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
print(np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)]))

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  This is separate from the ipykernel package so we can avoid doing imports until


In [539]:
#24
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
A = np.random.random((5,3))
B = np.random.random((3,2))
print(np.dot(A, B))

[[1.79573359 0.68937425]
 [1.20132121 0.7287269 ]
 [0.59042313 0.25621065]
 [1.98790932 0.98049882]
 [1.0533652  0.50521457]]


In [540]:
#25
#Given a 1D array, negate all elements which are between 3 and 8, in place.
A = np.arange(11)
A[(3 < A) & (A < 8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [541]:
#26
#What is the output of the following script?
from numpy import *
print(sum(range(5),-1))

10


In [542]:
#27
# Consider an integer vector Z, which of these expressions are legal?
Z = np.array([1,23,3],dtype=int)
print(Z ** Z)
print(2 << Z >>2)
print(Z < -Z)
print(1j*Z)
print(Z/1/1)

[                  1 8450172506621111015                  27]
[      1 4194304       4]
[False False False]
[0. +1.j 0.+23.j 0. +3.j]
[ 1. 23.  3.]


In [543]:
#28
#What are the result of the following expressions
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


In [544]:
#29
#How to round away from zero a float array ?
A = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(A)), A))


[ -6. -10.   3.   6.  -9.   5. -10.   5.  10.  -3.]


In [545]:
#30
#How to find common values between two arrays?
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print(np.intersect1d(A,B)) 

[1 2 7 9]


In [546]:
#31
#How to ignore all numpy warnings (not recommended)?
defaults = np.seterr(all="ignore")

In [547]:
#32
#Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [548]:
#33
#How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2021-12-07
2021-12-08
2021-12-09


In [549]:
#34
#How to get all the dates corresponding to the month of July 2016?
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [550]:
#35
#How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [551]:
#36
#Extract the integer part of a random array of positive numbers using 4 different methods
A= np.random.uniform(0,10,10)
print(A - A%1)
print(A // 1)
print(np.floor(A))
print(A.astype(int))
print(np.trunc(A))

[9. 1. 7. 4. 5. 7. 5. 2. 4. 6.]
[9. 1. 7. 4. 5. 7. 5. 2. 4. 6.]
[9. 1. 7. 4. 5. 7. 5. 2. 4. 6.]
[9 1 7 4 5 7 5 2 4 6]
[9. 1. 7. 4. 5. 7. 5. 2. 4. 6.]


In [552]:
#37
#Create a 5x5 matrix with row values ranging from 0 to 4
A = np.zeros((5,5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [553]:
#38
#Consider a generator function that generates 10 integers and use it to build an array
def generator():
    for x in range(10):
        yield x
print(np.fromiter(generator(),dtype=float,count=-1))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [554]:
#39
#Create a vector of size 10 with values ranging from 0 to 1, both excluded
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [555]:
#40
# Create a random vector of size 10 and sort it
print(np.random.random(10).sort())

None


In [556]:
#41
#How to sum a small array faster than np.sum?
np.add.reduce(np.arange(10))

45

In [557]:
#42
#Consider two random array A and B, check if they are equal 
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [558]:
#44
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10,2))
print(np.sqrt(Z[:,0]**2+Z[:,1]**2))
print(np.arctan2(Z[:,1], Z[:,0]))

[0.58627809 0.54055725 0.81892624 0.92631754 0.11825789 1.09044475
 0.92684923 0.53144013 0.7138255  0.90694008]
[1.44125202 0.83263468 0.57596798 1.22763652 0.09417107 0.63580046
 0.53150975 0.23908327 1.2692396  1.12275289]


In [559]:
#45
#Create random vector of size 10 and replace the maximum value by 0
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.46607953 0.9419173  0.         0.07238377 0.86873231 0.88898713
 0.33445344 0.95961623 0.4325251  0.93330655]


In [560]:
#46
#Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [561]:
#47
#Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
A = np.arange(8)
B = A + 0.5
C = 1.0 / np.subtract.outer(A, B)
print(np.linalg.det(C))

3638.1636371179666


In [562]:
#48
#Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [563]:
#49
#How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [564]:
#50
#How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
ind = (np.abs(Z-v)).argmin()
print(Z[ind])

46


In [565]:
#51
#Create a structured array representing a position (x,y) and a color (r,g,b)
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]), ('color',    [ ('r', float, 1), ('g', float, 1),('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  This is separate from the ipykernel package so we can avoid doing imports until


In [566]:
#52
#Consider a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(np.sqrt( (X-X.T)**2 + (Y-Y.T)**2))

[[0.         0.28115109 0.63079277 0.21102255 0.33636988 0.3088431
  0.18888672 0.60859136 0.79207936 0.42404008]
 [0.28115109 0.         0.34965799 0.41900951 0.28901501 0.53145037
  0.42306383 0.32783542 0.63249916 0.58129465]
 [0.63079277 0.34965799 0.         0.74899681 0.51965856 0.85910043
  0.76109552 0.02930913 0.57627883 0.86660715]
 [0.21102255 0.41900951 0.74899681 0.         0.29826431 0.1124478
  0.04494099 0.73236176 0.99538049 0.59170565]
 [0.33636988 0.28901501 0.51965856 0.29826431 0.         0.38677912
  0.33192747 0.51139791 0.92006215 0.75337651]
 [0.3088431  0.53145037 0.85910043 0.1124478  0.38677912 0.
  0.12006821 0.84311406 1.10007481 0.64396486]
 [0.18888672 0.42306383 0.76109552 0.04494099 0.33192747 0.12006821
  0.         0.74308382 0.98006371 0.55108266]
 [0.60859136 0.32783542 0.02930913 0.73236176 0.51139791 0.84311406
  0.74308382 0.         0.55484708 0.83799447]
 [0.79207936 0.63249916 0.57627883 0.99538049 0.92006215 1.10007481
  0.98006371 0.5548470

In [567]:
#53
#How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[33 17 41 30 78 28 90 59 22 39]


In [568]:
#54
#How to read the following file? s = StringIO('''1, 2, 3, 4, 5
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [569]:
#55
#What is the equivalent of enumerate for numpy arrays?
A = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(A):
    print(index, value)
for index in np.ndindex(A.shape):
    print(index, A[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [570]:
#56
#Generate a generic 2D Gaussian-like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
delta = 1.0
mu = 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * delta**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [571]:
#57
# How to randomly place p elements in a 2D array? 
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [572]:
#58
#Subtract the mean of each row of a matrix 
X = np.random.rand(5, 10)
print(X - X.mean(axis=1).reshape(-1, 1))

[[ 0.48466497  0.05943309  0.31056488  0.0969021  -0.44666335 -0.32086039
  -0.08092274  0.16511672 -0.12402015 -0.14421513]
 [-0.20589187  0.03409808 -0.18444364 -0.1943261   0.26831652 -0.06022202
  -0.13244959 -0.15614379  0.18416637  0.44689604]
 [-0.00366659 -0.0741202   0.05656117  0.05277573 -0.15399997  0.1161843
  -0.41068916  0.3847122   0.35563264 -0.32339012]
 [-0.11183125 -0.15801178  0.34090897  0.32706932  0.45550524 -0.10918779
  -0.07024167 -0.38827488  0.02801491 -0.31395106]
 [ 0.33595238  0.00643974  0.29713226  0.01717236  0.0095112  -0.42335543
  -0.14527565  0.00378102 -0.41961411  0.31825624]]


In [573]:
#59
#How to sort an array by the nth column?
A = np.random.randint(0,10,(3,3))
print(A)
print(A[A[:,1].argsort()])

[[6 5 3]
 [5 2 1]
 [2 9 9]]
[[5 2 1]
 [6 5 3]
 [2 9 9]]


In [574]:
#60
#How to tell if a given 2D array has null columns?
print((np.random.randint(0,3,(3,10)).any(axis=0)).any())

True


In [575]:
#61
#Find the nearest value from a given value in an array 
Z = np.random.uniform(0,1,10)
print(Z.flat[np.abs(Z - 0.5).argmin()])

0.468127445849677


In [576]:
#62
#Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [577]:
#63
#Create an array class that has a name attribute 
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

print (NamedArray(np.arange(10), "range_10").name)

range_10


In [578]:
#64
#Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[2. 3. 3. 4. 5. 6. 1. 2. 1. 3.]
[ 3.  5.  5.  7.  9. 11.  1.  3.  1.  5.]


In [579]:
#65
#How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
F = np.bincount([1,3,9,3,4,1],[1,2,3,4,5,6])
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [580]:
#66
#Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [581]:
#67
#Considering a four dimensions array, how to get sum over the last two axis at once?
sum = np.random.randint(0,10,(3,4,3,4)).sum(axis=(-2,-1))
print(sum)

[[46 62 63 49]
 [70 49 77 51]
 [49 49 51 43]]


In [582]:
#69
#How to get the diagonal of a dot product?
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)

array([0.88460563, 0.81018959, 0.64543434, 1.73071894, 2.07085958])

In [583]:
#70
#Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 
a = np.array([1,2,3,4,5])
a0 = np.zeros(len(a) + (len(a)-1)*(3))
a0[::4] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [584]:
#71
#Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [585]:
#72
#How to swap two rows of an array? 
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [586]:
#73
#Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
A = np.roll(faces.repeat(2,axis=1),-1,axis=1)
A = A.reshape(len(A)*3,2)
A = np.sort(A,axis=1)
B = A.view( dtype=[('p0',A.dtype),('p1',A.dtype)] )
print(np.unique(B))

[( 0, 46) ( 0, 90) ( 2,  8) ( 2, 40) ( 5, 18) ( 5, 41) ( 8, 10) ( 8, 36)
 ( 8, 40) ( 8, 52) ( 8, 68) (10, 52) (18, 41) (18, 48) (18, 59) (18, 85)
 (18, 88) (26, 67) (26, 85) (36, 68) (44, 66) (44, 91) (46, 90) (48, 88)
 (50, 77) (50, 80) (59, 85) (66, 91) (67, 85) (77, 80)]


In [587]:
#74
#Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?
A = np.bincount([1,1,2,3,4,4,6])
B = np.repeat(np.arange(len(A)), A)
print(B)

[1 1 2 3 4 4 6]


In [588]:
#75
#How to compute averages using a sliding window over an array?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
print(moving_average(np.arange(20), n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [589]:
#76
#Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
print(rolling(np.arange(10), 3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [590]:
#77
#How to negate a boolean, or to change the sign of a float inplace? 
np.logical_not(np.random.randint(0,2,100), out=np.random.randint(0,2,100))
np.negative(np.random.uniform(-1.0,1.0,100), out=np.random.uniform(-1.0,1.0,100))

array([-0.61771432, -0.54548166,  0.40255463,  0.45417541,  0.2518975 ,
       -0.9682254 ,  0.19769515, -0.53158541, -0.68298894,  0.23990624,
        0.78847407, -0.71581924, -0.25851095,  0.48063742,  0.60435272,
        0.4630245 ,  0.46261627, -0.03318817,  0.32127394, -0.56114308,
       -0.28198602, -0.98320133, -0.03789774, -0.9310324 ,  0.7525241 ,
        0.00220128, -0.83041428, -0.60938916, -0.4490199 ,  0.60818497,
       -0.75628217, -0.04224149, -0.69167886, -0.64791882, -0.02928206,
        0.08570682,  0.84719126,  0.58087453, -0.16179378, -0.26487818,
        0.91178004, -0.56763236,  0.25250242, -0.85661897, -0.87374495,
        0.93174239, -0.31002392, -0.53269686,  0.88155918,  0.10396748,
       -0.27812778,  0.10678233,  0.88235582,  0.27853063, -0.26383844,
        0.08095153, -0.01321366, -0.01103537,  0.60403904, -0.00368611,
        0.99713391, -0.02625006, -0.37229693,  0.49585374,  0.32691486,
        0.14766098, -0.84449762, -0.63464892, -0.19419304,  0.32

In [591]:
#78
#Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.79791646 13.89588302  2.09768403  4.16507878 12.73392388 18.64501442
 16.27372104 15.65433288  0.98757195 10.76972249]


In [592]:
#79
# Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[18.41049996 11.28618435  4.29025907  3.31701361  1.79860118  8.17288147
  15.03580984  6.59594177 12.04023025 17.19525778]
 [ 3.06655964  5.35493362  6.98744401  0.23163235  0.14382835  0.96775365
  11.31444872 11.59540473  6.24504693  0.27298713]
 [14.86004059  8.23643938  7.67010325  1.67410891  6.61050031  3.29523371
  10.04503778  6.8909633  12.22500326 14.58805443]
 [ 0.75527025  7.06793412  2.75055138  4.47194331  5.04276108  3.29920863
   6.66126159  9.87166867  4.62317948  1.48233491]
 [ 1.25226755  7.86458008  6.09897992 12.24901095 13.78149896  9.77633233
   0.9447231   4.4867697   0.5968424   1.29437259]
 [ 6.17718817  0.62836778 14.81581961 13.08044604 17.40696388  8.03305286
   1.38802351  6.77024249 11.85121348  7.9437126 ]
 [ 7.00286236  0.52185233  7.92916062  7.56310072 10.99664478  3.62866082
   3.97898944  2.11362003  7.31038764  7.08857525]
 [ 8.93896162  3.05605132 12.60105973  9.49389397 14.02329582  4.46097972
   2.20845953  6.85232967 12.01293632 10.07100928]


In [593]:
#80
#Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 4 0 1 2 9 7 1 1 6]
 [1 5 4 7 6 7 0 3 5 6]
 [1 6 7 0 7 1 4 7 4 4]
 [8 0 1 5 4 9 8 4 4 8]
 [4 2 7 8 0 1 3 5 8 2]
 [7 6 4 8 8 5 8 5 4 5]
 [0 0 4 1 4 5 7 3 3 1]
 [7 9 7 7 7 4 7 4 3 0]
 [9 5 9 3 4 6 4 3 7 1]
 [9 9 8 0 3 2 4 5 4 2]]
[[0 0 0 0 0]
 [0 3 4 0 1]
 [0 1 5 4 7]
 [0 1 6 7 0]
 [0 8 0 1 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [594]:
#81
#Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
print(stride_tricks.as_strided(np.arange(1,15,dtype=np.uint32),(11,4),(4,4)))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [595]:
#82
#Compute a matrix rank
A = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(A) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [596]:
#83
#How to find the most frequent value in an array?
print(np.bincount(np.random.randint(0,10,50)).argmax())

1


In [597]:
#84
#Extract all the contiguous 3x3 blocks from a random 10x10 matrix
A = np.random.randint(0,5,(10,10))
C = stride_tricks.as_strided(A, shape=(1 + (Z.shape[0]-3), 1 + (Z.shape[1]-3), 3, 3), strides=A.strides + A.strides)
print(C)

[[[[2 0 3]
   [0 2 2]
   [4 3 1]]

  [[0 3 1]
   [2 2 3]
   [3 1 4]]

  [[3 1 0]
   [2 3 4]
   [1 4 1]]

  [[1 0 0]
   [3 4 1]
   [4 1 4]]

  [[0 0 2]
   [4 1 1]
   [1 4 0]]

  [[0 2 3]
   [1 1 2]
   [4 0 0]]

  [[2 3 4]
   [1 2 4]
   [0 0 4]]

  [[3 4 2]
   [2 4 1]
   [0 4 0]]]


 [[[0 2 2]
   [4 3 1]
   [4 2 2]]

  [[2 2 3]
   [3 1 4]
   [2 2 3]]

  [[2 3 4]
   [1 4 1]
   [2 3 2]]

  [[3 4 1]
   [4 1 4]
   [3 2 2]]

  [[4 1 1]
   [1 4 0]
   [2 2 3]]

  [[1 1 2]
   [4 0 0]
   [2 3 3]]

  [[1 2 4]
   [0 0 4]
   [3 3 1]]

  [[2 4 1]
   [0 4 0]
   [3 1 3]]]


 [[[4 3 1]
   [4 2 2]
   [1 0 2]]

  [[3 1 4]
   [2 2 3]
   [0 2 0]]

  [[1 4 1]
   [2 3 2]
   [2 0 0]]

  [[4 1 4]
   [3 2 2]
   [0 0 1]]

  [[1 4 0]
   [2 2 3]
   [0 1 0]]

  [[4 0 0]
   [2 3 3]
   [1 0 2]]

  [[0 0 4]
   [3 3 1]
   [0 2 2]]

  [[0 4 0]
   [3 1 3]
   [2 2 2]]]


 [[[4 2 2]
   [1 0 2]
   [0 4 3]]

  [[2 2 3]
   [0 2 0]
   [4 3 2]]

  [[2 3 2]
   [2 0 0]
   [3 2 4]]

  [[3 2 2]
   [0 0 1]
   [2 4 1]]

  [[2 2 3]
   

In [598]:
#85
# Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  7  4 15  9]
 [ 7  6  7 12 14]
 [ 4  7  4 42  9]
 [15 12 42  6 12]
 [ 9 14  9 12  2]]


In [599]:
#86
#Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [600]:
#87
#Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [601]:
#88
#How to implement the Game of Life using numpy arrays? 
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [602]:
#89
# How to get the n largest values of an array
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9996 9997 9998 9995]


In [603]:
#90
# Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [604]:
#91
#How to create a record array from a regular array?
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [605]:
#92
#Consider a large vector Z, compute Z to the power of 3 using 3 different methods
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.73 s per loop
10 loops, best of 5: 146 ms per loop
10 loops, best of 5: 122 ms per loop


In [606]:
#93
#Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 5 6 7]


In [607]:
#94
#Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
A = np.random.randint(0,5,(10,3))
E = np.all(A[:,1:] == A[:,:-1], axis=1)
U = A[~E]
print(U)

[[0 2 3]
 [2 1 4]
 [4 1 2]
 [1 3 3]
 [3 2 1]
 [0 3 4]
 [4 1 3]
 [0 3 1]
 [2 1 0]]


In [608]:
#95
#Convert a vector of ints into a matrix binary representation
B = ((np.array([0, 1, 2, 3, 15, 16, 32, 64, 128]).reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [609]:
#96
#Given a two dimensional array, how to extract unique rows?
T = np.ascontiguousarray(np.random.randint(0,2,(6,3))).view(np.dtype((np.void, np.random.randint(0,2,(6,3)).dtype.itemsize * np.random.randint(0,2,(6,3)).shape[1])))
a, idx = np.unique(T, return_index=True)
p = np.random.randint(0,2,(6,3))[idx]
print(p)

[[1 1 1]
 [0 1 0]
 [1 0 0]]


In [610]:
#97
#Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)  

array([[0.3741034 , 0.2198632 , 0.1496465 , 0.49986818, 0.7921938 ,
        0.83585663, 0.92074563, 0.66689881, 0.16035259, 0.10542066],
       [0.0839835 , 0.04935769, 0.03359455, 0.11221678, 0.17784176,
        0.18764374, 0.20670071, 0.14971394, 0.03599799, 0.02366617],
       [0.08058699, 0.04736154, 0.0322359 , 0.10767844, 0.17064938,
        0.18005495, 0.1983412 , 0.14365913, 0.03454214, 0.02270905],
       [0.20067057, 0.11793551, 0.08027099, 0.2681313 , 0.42493595,
        0.44835686, 0.49389167, 0.35772721, 0.08601378, 0.05654807],
       [0.20371806, 0.11972654, 0.08149002, 0.27220328, 0.43138924,
        0.45516584, 0.50139216, 0.36315984, 0.08732003, 0.05740684],
       [0.3022397 , 0.1776284 , 0.12090004, 0.40384559, 0.64001668,
        0.67529206, 0.74387425, 0.53879034, 0.12954953, 0.0851698 ],
       [0.20294831, 0.11927415, 0.08118212, 0.27117477, 0.42975925,
        0.45344601, 0.49949766, 0.36178765, 0.08699009, 0.05718993],
       [0.0203753 , 0.01197471, 0.0081504

In [611]:
#98
#Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [612]:
#99
#Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0], [2.0, 0.0, 1.0, 1.0], [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [613]:
#100
#Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
A = np.random.randn(100) 
idx = np.random.randint(0, A.size, (1000, A.size))
means = A[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30564988  0.05728395]
